//
// Generated by JTB 1.3.2
//
package br.com.seimos.minijava.visitor;

import br.com.seimos.minijava.syntaxtree.*;
import java.util.*;

/**
 * A skeleton output formatter for your language grammar.  Using the
 * add() method along with force(), indent(), and outdent(), you can
 * easily specify how this visitor will format the given syntax tree.
 * See the JTB documentation for more details.
 *
 * Pass your syntax tree to this visitor, and then to the TreeDumper
 * visitor in order to "pretty print" your tree.
 */
public class TreeFormatter extends DepthFirstVisitor {
   private Vector<FormatCommand> cmdQueue = new Vector<FormatCommand>();
   private boolean lineWrap;
   private int wrapWidth;
   private int indentAmt;
   private int curLine = 1;
   private int curColumn = 1;
   private int curIndent = 0;

   /**
    * The default constructor assumes an indentation amount of 3 spaces
    * and no line-wrap.  You may alternately use the other constructor to
    * specify your own indentation amount and line width.
    */
   public TreeFormatter() { this(3, 0); }

   /**
    * This constructor accepts an indent amount and a line width which is
    * used to wrap long lines.  If a token's beginColumn value is greater
    * than the specified wrapWidth, it will be moved to the next line and
    * indented one extra level.  To turn off line-wrapping, specify a
    * wrapWidth of 0.
    *
    * @param   indentAmt   Amount of spaces per indentation level.
    * @param   wrapWidth   Wrap lines longer than wrapWidth.  0 for no wrap.
    */
   public TreeFormatter(int indentAmt, int wrapWidth) {
      this.indentAmt = indentAmt;
      this.wrapWidth = wrapWidth;

      if ( wrapWidth > 0 )
         lineWrap = true;
      else
         lineWrap = false;
   }

   /**
    * Accepts a NodeListInterface object and performs an optional format
    * command between each node in the list (but not after the last node).
    */
   protected void processList(NodeListInterface n) {
      processList(n, null);
   }

   protected void processList(NodeListInterface n, FormatCommand cmd) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         if ( cmd != null && e.hasMoreElements() )
            cmdQueue.addElement(cmd);
      }
   }

   /**
    * A Force command inserts a line break and indents the next line to
    * the current indentation level.  Use "add(force());".
    */
   protected FormatCommand force() { return force(1); }
   protected FormatCommand force(int i) {
      return new FormatCommand(FormatCommand.FORCE, i);
   }

   /**
    * An Indent command increases the indentation level by one (or a
    * user-specified amount).  Use "add(indent());".
    */
   protected FormatCommand indent() { return indent(1); }
   protected FormatCommand indent(int i) {
      return new FormatCommand(FormatCommand.INDENT, i);
   }

   /**
    * An Outdent command is the reverse of the Indent command: it reduces
    * the indentation level.  Use "add(outdent());".
    */
   protected FormatCommand outdent() { return outdent(1); }
   protected FormatCommand outdent(int i) {
      return new FormatCommand(FormatCommand.OUTDENT, i);
   }

   /**
    * A Space command simply adds one or a user-specified number of
    * spaces between tokens.  Use "add(space());".
    */
   protected FormatCommand space() { return space(1); }
   protected FormatCommand space(int i) {
      return new FormatCommand(FormatCommand.SPACE, i);
   }

   /**
    * Use this method to add FormatCommands to the command queue to be
    * executed when the next token in the tree is visited.
    */
   protected void add(FormatCommand cmd) {
      cmdQueue.addElement(cmd);
   }

   /**
    * Executes the commands waiting in the command queue, then inserts the
    * proper location information into the current NodeToken.
    *
    * If there are any special tokens preceding this token, they will be
    * given the current location information.  The token will follow on
    * the next line, at the proper indentation level.  If this is not the
    * behavior you want from special tokens, feel free to modify this
    * method.
    */
   public void visit(NodeToken n) {
      for ( Enumeration<FormatCommand> e = cmdQueue.elements(); e.hasMoreElements(); ) {
         FormatCommand cmd = e.nextElement();
         switch ( cmd.getCommand() ) {
         case FormatCommand.FORCE :
            curLine += cmd.getNumCommands();
            curColumn = curIndent + 1;
            break;
         case FormatCommand.INDENT :
            curIndent += indentAmt * cmd.getNumCommands();
            break;
         case FormatCommand.OUTDENT :
            if ( curIndent >= indentAmt )
               curIndent -= indentAmt * cmd.getNumCommands();
            break;
         case FormatCommand.SPACE :
            curColumn += cmd.getNumCommands();
            break;
         default :
            throw new TreeFormatterException(
               "Invalid value in command queue.");
         }
      }

      cmdQueue.removeAllElements();

      //
      // Handle all special tokens preceding this NodeToken
      //
      if ( n.numSpecials() > 0 )
         for ( Enumeration<NodeToken> e = n.specialTokens.elements();
               e.hasMoreElements(); ) {
            NodeToken special = e.nextElement();

            //
            // -Place the token.
            // -Move cursor to next line after the special token.
            // -Don't update curColumn--want to keep current indent level.
            //
            placeToken(special, curLine, curColumn);
            curLine = special.endLine + 1;
         }

      placeToken(n, curLine, curColumn);
      curLine = n.endLine;
      curColumn = n.endColumn;
   }

   /**
    * Inserts token location (beginLine, beginColumn, endLine, endColumn)
    * information into the NodeToken.  Takes into account line-wrap.
    * Does not update curLine and curColumn.
    */
   private void placeToken(NodeToken n, int line, int column) {
      int length = n.tokenImage.length();

      //
      // Find beginning of token.  Only line-wrap for single-line tokens
      //
      if ( !lineWrap || n.tokenImage.indexOf('\n') != -1 ||
           column + length <= wrapWidth )
         n.beginColumn = column;
      else {
         ++line;
         column = curIndent + indentAmt + 1;
         n.beginColumn = column;
      }

      n.beginLine = line;

      //
      // Find end of token; don't count \n if it's the last character
      //
      for ( int i = 0; i < length; ++i ) {
         if ( n.tokenImage.charAt(i) == '\n' && i < length - 1 ) {
            ++line;
            column = 1;
         }
         else
            ++column;
      }

      n.endLine = line;
      n.endColumn = column;
   }

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * f0 -> MainClass()
    * f1 -> ClassDeclarationList()
    * f2 -> &lt;EOF&gt;
    * </PRE>
    */
   public void visit(Program n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * <PRE>
    * f0 -> &lt;CLASS&gt;
    * f1 -> &lt;IDENTIFIER&gt;
    * f2 -> &lt;LBRACE&gt;
    * f3 -> &lt;PUBLIC&gt;
    * f4 -> &lt;STATIC&gt;
    * f5 -> &lt;VOID&gt;
    * f6 -> &lt;MAIN&gt;
    * f7 -> &lt;LPAREN&gt;
    * f8 -> &lt;STRING&gt;
    * f9 -> &lt;LBRACKET&gt;
    * f10 -> &lt;RBRACKET&gt;
    * f11 -> &lt;IDENTIFIER&gt;
    * f12 -> &lt;RPAREN&gt;
    * f13 -> &lt;LBRACE&gt;
    * f14 -> Statement()
    * f15 -> &lt;RBRACE&gt;
    * f16 -> &lt;RBRACE&gt;
    * </PRE>
    */
   public void visit(MainClass n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
      n.f15.accept(this);
      n.f16.accept(this);
   }

   /**
    * <PRE>
    * f0 -> &lt;CLASS&gt;
    * f1 -> &lt;IDENTIFIER&gt;
    * f2 -> ( &lt;EXTENDS&gt; &lt;IDENTIFIER&gt; )?
    * f3 -> &lt;LBRACE&gt;
    * f4 -> VarDeclarationList()
    * f5 -> MethodDeclarationList()
    * f6 -> &lt;RBRACE&gt;
    * </PRE>
    */
   public void visit(ClassDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
      if ( n.f2.present() ) {
         n.f2.accept(this);
      }
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * <PRE>
    * f0 -> [ ClassDeclaration() ClassDeclarationList() ]
    * </PRE>
    */
   public void visit(ClassDeclarationList n) {
      if ( n.f0.present() ) {
         n.f0.accept(this);
      }
   }

   /**
    * <PRE>
    * f0 -> [ Statement() StatementList() ]
    * </PRE>
    */
   public void visit(StatementList n) {
      if ( n.f0.present() ) {
         n.f0.accept(this);
      }
   }

   /**
    * <PRE>
    * f0 -> &lt;LBRACE&gt; StatementList() &lt;RBRACE&gt;
    *       | &lt;IF&gt; &lt;LPAREN&gt; Expression() &lt;RPAREN&gt; Statement() &lt;ELSE&gt; Statement()
    *       | &lt;WHILE&gt; &lt;LPAREN&gt; Expression() &lt;RPAREN&gt; Statement()
    *       | &lt;SYSO&gt; &lt;LPAREN&gt; Expression() &lt;RPAREN&gt; &lt;SEMICOLON&gt;
    *       | &lt;IDENTIFIER&gt; &lt;EQUALS&gt; Expression() &lt;SEMICOLON&gt;
    *       | &lt;IDENTIFIER&gt; &lt;LBRACKET&gt; Expression() &lt;RBRACKET&gt; &lt;EQUALS&gt; Expression() &lt;SEMICOLON&gt;
    * </PRE>
    */
   public void visit(Statement n) {
      n.f0.accept(this);
   }

   /**
    * <PRE>
    * f0 -> Type()
    * f1 -> &lt;IDENTIFIER&gt;
    * f2 -> &lt;SEMICOLON&gt;
    * </PRE>
    */
   public void visit(VarDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * <PRE>
    * f0 -> [ VarDeclaration() VarDeclarationList() ]
    * </PRE>
    */
   public void visit(VarDeclarationList n) {
      if ( n.f0.present() ) {
         n.f0.accept(this);
      }
   }

   /**
    * <PRE>
    * f0 -> &lt;PUBLIC&gt;
    * f1 -> Type()
    * f2 -> &lt;IDENTIFIER&gt;
    * f3 -> &lt;LPAREN&gt;
    * f4 -> FormalList()
    * f5 -> &lt;RPAREN&gt;
    * f6 -> &lt;LBRACE&gt;
    * f7 -> VarDeclarationList()
    * f8 -> StatementList()
    * f9 -> &lt;RETURN&gt;
    * f10 -> Expression()
    * f11 -> &lt;SEMICOLON&gt;
    * f12 -> &lt;RBRACE&gt;
    * </PRE>
    */
   public void visit(MethodDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
   }

   /**
    * <PRE>
    * f0 -> [ MethodDeclaration() MethodDeclarationList() ]
    * </PRE>
    */
   public void visit(MethodDeclarationList n) {
      if ( n.f0.present() ) {
         n.f0.accept(this);
      }
   }

   /**
    * <PRE>
    * f0 -> AndExpression()
    *       | LessThanExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | ArrayLookupExpression()
    *       | ArrayLengthExpression()
    *       | MethodCallExpression()
    *       | PrimaryExpression()
    * </PRE>
    */
   public void visit(Expression n) {
      n.f0.accept(this);
   }

   /**
    * <PRE>
    * f0 -> &lt;INTEGER_LITERAL&gt;
    *       | &lt;TRUE&gt;
    *       | &lt;FALSE&gt;
    *       | &lt;IDENTIFIER&gt;
    *       | &lt;THIS&gt;
    *       | &lt;NEW&gt; &lt;INTEGER&gt; &lt;LBRACKET&gt; Expression() &lt;RBRACKET&gt;
    *       | &lt;NEW&gt; &lt;IDENTIFIER&gt; &lt;LPAREN&gt; &lt;RPAREN&gt;
    *       | &lt;NOT&gt; Expression()
    *       | &lt;LPAREN&gt; Expression() &lt;RPAREN&gt;
    * </PRE>
    */
   public void visit(PrimaryExpression n) {
      n.f0.accept(this);
   }

   /**
    * <PRE>
    * f0 -> [ Expression() ExpressionRestList() ]
    * </PRE>
    */
   public void visit(ExpressionList n) {
      if ( n.f0.present() ) {
         n.f0.accept(this);
      }
   }

   /**
    * <PRE>
    * f0 -> &lt;INTEGER&gt; &lt;LBRACKET&gt; &lt;RBRACKET&gt;
    *       | &lt;BOOLEAN&gt;
    *       | &lt;INTEGER&gt;
    *       | &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(Type n) {
      n.f0.accept(this);
   }

   /**
    * <PRE>
    * f0 -> [ Type() &lt;IDENTIFIER&gt; FormalRestList() ]
    * </PRE>
    */
   public void visit(FormalList n) {
      if ( n.f0.present() ) {
         n.f0.accept(this);
      }
   }

   /**
    * <PRE>
    * f0 -> &lt;COMMA&gt;
    * f1 -> Type()
    * f2 -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(FormalRest n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * <PRE>
    * f0 -> [ FormalRest() FormalRestList() ]
    * </PRE>
    */
   public void visit(FormalRestList n) {
      if ( n.f0.present() ) {
         n.f0.accept(this);
      }
   }

   /**
    * <PRE>
    * f0 -> &lt;COMMA&gt;
    * f1 -> Expression()
    * </PRE>
    */
   public void visit(ExpressionRest n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * <PRE>
    * f0 -> [ ExpressionRest() ExpressionRestList() ]
    * </PRE>
    */
   public void visit(ExpressionRestList n) {
      if ( n.f0.present() ) {
         n.f0.accept(this);
      }
   }

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> &lt;AND&gt;
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public void visit(AndExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> &lt;LT&gt;
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public void visit(LessThanExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> &lt;PLUS&gt;
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public void visit(PlusExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> &lt;MINUS&gt;
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public void visit(MinusExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> &lt;TIMES&gt;
    * f2 -> PrimaryExpression()
    * </PRE>
    */
   public void visit(TimesExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> &lt;LBRACKET&gt;
    * f2 -> Expression()
    * f3 -> &lt;RBRACKET&gt;
    * </PRE>
    */
   public void visit(ArrayLookupExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> &lt;DOT&gt;
    * f2 -> &lt;LENGTH&gt;
    * </PRE>
    */
   public void visit(ArrayLengthExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * <PRE>
    * f0 -> PrimaryExpression()
    * f1 -> &lt;DOT&gt;
    * f2 -> &lt;IDENTIFIER&gt;
    * f3 -> &lt;LPAREN&gt;
    * f4 -> ExpressionList()
    * f5 -> &lt;RPAREN&gt;
    * </PRE>
    */
   public void visit(MethodCallExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

}

class FormatCommand {
   public static final int FORCE = 0;
   public static final int INDENT = 1;
   public static final int OUTDENT = 2;
   public static final int SPACE = 3;

   private int command;
   private int numCommands;

   FormatCommand(int command, int numCommands) {
      this.command = command;
      this.numCommands = numCommands;
   }

   public int getCommand()             { return command; }
   public int getNumCommands()         { return numCommands; }
   public void setCommand(int i)       { command = i; }
   public void setNumCommands(int i)   { numCommands = i; }
}

class TreeFormatterException extends RuntimeException {
   TreeFormatterException()         { super(); }
   TreeFormatterException(String s) { super(s); }
}
