//
// Generated by JTB 1.3.2
//

package br.com.seimos.minijava.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> PrimaryExpression()
 * f1 -> &lt;DOT&gt;
 * f2 -> &lt;LENGTH&gt;
 * </PRE>
 */
public class ArrayLengthExpression implements Node {
	public PrimaryExpression f0;
	public NodeToken f1;
	public NodeToken f2;

	public ArrayLengthExpression(PrimaryExpression n0, NodeToken n1, NodeToken n2) {
		f0 = n0;
		f1 = n1;
		f2 = n2;
	}

	public ArrayLengthExpression(PrimaryExpression n0) {
		f0 = n0;
		f1 = new NodeToken(".");
		f2 = new NodeToken("length");
	}

	public void accept(br.com.seimos.minijava.visitor.Visitor v) {
		v.visit(this);
	}

	public <R, A> R accept(br.com.seimos.minijava.visitor.GJVisitor<R, A> v, A argu) {
		return v.visit(this, argu);
	}

	public <R> R accept(br.com.seimos.minijava.visitor.GJNoArguVisitor<R> v) {
		return v.visit(this);
	}

	public <A> void accept(br.com.seimos.minijava.visitor.GJVoidVisitor<A> v, A argu) {
		v.visit(this, argu);
	}
}
