//
// Generated by JTB 1.3.2
//

package br.com.seimos.minijava.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> MainClass()
 * f1 -> ClassDeclarationList()
 * f2 -> &lt;EOF&gt;
 * </PRE>
 */
public class Program implements Node {
	public MainClass f0;
	public ClassDeclarationList f1;
	public NodeToken f2;

	public Program(MainClass n0, ClassDeclarationList n1, NodeToken n2) {
		f0 = n0;
		f1 = n1;
		f2 = n2;
	}

	public Program(MainClass n0, ClassDeclarationList n1) {
		f0 = n0;
		f1 = n1;
		f2 = new NodeToken("");
	}

	public void accept(br.com.seimos.minijava.visitor.Visitor v) {
		v.visit(this);
	}

	public <R, A> R accept(br.com.seimos.minijava.visitor.GJVisitor<R, A> v, A argu) {
		return v.visit(this, argu);
	}

	public <R> R accept(br.com.seimos.minijava.visitor.GJNoArguVisitor<R> v) {
		return v.visit(this);
	}

	public <A> void accept(br.com.seimos.minijava.visitor.GJVoidVisitor<A> v, A argu) {
		v.visit(this, argu);
	}
}
